### PR TITLE
Use standard BSD3 license text

### PR DESCRIPTION
**Pull request by cxong**

### CODE REVIEW

**Comment by textbrowser** [comment]
Like, which software is the proposed license referring to?

**Comment by textbrowser** [comment]
"This software" is silly. The license should refer to a specific software instead of a generic software. :)

**Comment by cxong** [comment]
This is the standard text from https://choosealicense.com/licenses/bsd-3-clause/

Instructions for applying it:

> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.

Using the standard text helps with tools that autodetect licenses such as [licensee](https://github.com/licensee/licensee) (used by github to display licenses of projects). See https://github.com/flutter/flutter for example

**Comment by textbrowser** [comment]
Why should we write text for computers to understand when a clearer license, one which mentions the name of the software, is better for people?

**Comment by cxong** [comment]
"this software" is mentioned 3 times in the license; it is important to keep this consistent

**Comment by textbrowser** [comment]
:)

**Pull request merged**
